name: DeviseInvitable

on:
  workflow_dispatch:

jobs:
  devise_invitable:
    runs-on: ubuntu-latest
    env:
      REPOS: ${{ github.job }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout repos
        run: git submodule update --init repos/${REPOS}
      - name: Pull latest repos
        run: git submodule update --remote repos/${REPOS}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Execute GitStats
        run: bundle exec git_stats generate -p repos/${REPOS} -o docs/git_stats/${REPOS} --silent
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update of ${REPOS} repository statistics
          file_pattern: docs/* repos/${REPOS}
